/* 01/08/2017 11:57:09 http://www.COBOLware.com */
   CREATE TABLE FILENAME
        ( CODIGO    NUMBER(5),
          DESCRICAO VARCHAR2(30),
          PRECO     DECIMAL(10,2),
          TIPO      NUMBER(1),
          IMPORTADO NUMBER(1),
          GARANTIA  NUMBER(1),
          DURAVEL   NUMBER(1),
     CONSTRAINTS PK_FILENAME
      PRIMARY KEY ( CODIGO )
           USING INDEX ) TABLESPACE TS_USER;
     CREATE UNIQUE INDEX FILENAME_DESCRICAO
         ON FILENAME
         ( RPAD(DESCRICAO,30,' ')
        || LPAD(ABS(CODIGO),5,0) ) TABLESPACE TS_INDEX;
     CREATE INDEX FILENAME_DESCRICAO_key
         ON FILENAME
         ( DESCRICAO ) TABLESPACE TS_INDEX;
