                EXEC COBOLware OBJECT PUSH-BUTTON SMALL
                          LINE 23 COLUMN 03 WIDTH 15
                          CAPTION " pgup-~Anterior "
                          KEY CODE-PAGE-UP TAB-OFF
                END-EXEC
                EXEC COBOLware OBJECT PUSH-BUTTON SMALL
                          LINE 23 COLUMN 18 WIDTH 14
                          CAPTION " pgdn-~Pr¢ximo "
                          KEY CODE-PAGE-DOWN TAB-OFF
                END-EXEC
