#!/bin/sh
#-----------------------------------------------------------------------+
# Configurando o COBOLware 6.1                                          !
#-----------------------------------------------------------------------+
clear
echo "Este comando visa testar o ambiente sem necessidade de alterar o profile"
echo "Para evitar excessos de processos shell inserir na profile os sets a seguir:"
echo ' '
if test "$TERM" = "linux"
   then echo 'Em algumas modalidades de Linux pode ser preciso configurar:'
   echo 'LD_ASSUME_KERNEL="2.4.1";export LD_ASSUME_KERNEL'
   echo 'evitando o erro:"rts32: Fatal Error while attempting to process error 173"'
   echo ' '
fi
if test -z "$COBRUN"
   then export COBRUN='cobrun -F'
   echo "COBRUN='cobrun -F';export COBRUN"
fi
if test -z "$COBOLWARE"
   then COBOLWARE=`pwd`
        echo 'COBOLWARE='$COBOLWARE";export COBOLWARE" 
        if test -z "$COBDIR"
           then if test -f /opt/lib/cobol/ADISCTRL
                   then CWD=/opt/lib/cobol
                   else if test -f /opt/cobol/ADISCTRL
                           then CWD=/opt/cobol
                           else if test -f /cobol/ADISCTRL
                                   then CWD=/cobol
                                   else if test -f /home/cob41/ADISCTRL
                                           then CWD=/home/cob41
                                           else if test -f /opt/cobol/cobdir/ADISCTRL
                                                   then CWD=/opt/cobol/cobdir
                                                fi
                                        fi
                                fi
                        fi
                fi
                COBDIR=$CWD
                echo "COBDIR="$CWD";export COBDIR"
                if test -z "$LD_LIBRARY_PATH"
                   then LD_LIBRARY_PATH=$COBDIR/coblib
                   else LD_LIBRARY_PATH=$COBDIR/coblib:$LD_LIBRARY_PATH
                fi
                echo "LD_LIBRARY_PATH="$LD_LIBRARY_PATH";export LD_LIBRARY_PATH"
                if test -z "$SHLIB_PATH"
                   then SHLIB_PATH=$CWD/lib
                        export SHLIB_PATH
                        echo "SHLIB_PATH="$SHLIB_PATH";export SHLIB_PATH"
                fi
                echo 'PATH=$COBOLWARE:$COBDIR:$SHLIB_PATH:$LD_LIBRARY_PATH:$PATH'";export PATH"
                PATH=$COBDIR:$SHLIB_PATH:$LD_LIBRARY_PATH:$PATH
                export COBDIR LD_LIBRARY_PATH PATH
        fi
        if test -z "$CIL"
           then CIL=$COBOLWARE/cil
        fi
        if test -z "$dd_ADISCTRL"
           then dd_ADISCTRL=$COBOLWARE/adisctrl.unix
                export dd_ADISCTRL
                echo 'dd_ADISCTRL='$dd_ADISCTRL';export dd_ADISCTRL'
        fi
        if test -z "$CWMENU"
           then CWMENU=$COBOLWARE/cobware.lbr/CWMENU
                export CWMENU
                echo 'CWMENU='$CWMENU';export CWMENU'
        fi
        if test -z "$TEMP"
           then TEMP=$HOME/temp
                export TEMP
                echo 'TEMP=$HOME/temp;export TEMP'
                if ! test -f $TEMP
                   then mkdir $TEMP>/dev/null 2>/dev/null
                fi
        fi
        EDITOR="vi"
        PATH=$PATH:$COBOLWARE:$CIL
        if test -z "$COBPATH"
            then COBPATH=$CWD
                 echo 'COBPATH='$COBPATH';export COBPATH'
        fi
        if test -z "$dd_cobkeymp"
           then dd_cobkeymp=$COBOLWARE/cobkeymp
                export dd_cobkeymp
                echo 'dd_cobkeymp='$dd_cobkeymp';export dd_cobkeymp'
        fi
        export CIL COBOLWARE
        export EDITOR PATH COBPATH
        if test "$TERM" = "linux"
           then if test -z "$SSH_TTY"
                   then charset -v G0 cp850 2>/dev/null
                        setfont cp850-8x16 -m cp850 2>/dev/null
                fi
           if ! test -f /usr/lib/libstdc++-libc6.1-1.so.2
              then ./lastln /usr/lib/libstdc++-libc6.1-1.so.2 /usr/lib/libstdc++.so* 
           fi
        fi
#-----------------------------------------------------------------------+
# Fim da configuracao                                                   !
#-----------------------------------------------------------------------+

#-----------------------------------------------------------------------+
# Funcao de cada variavel:                                              +
#                                                                       +
#              COBOLware:                                               +
#                                                                       +
# CIL:         Diretorio dos programas compilados (.int e .gnt)         +
# COBOLWARE:   Diretorio dos utilitarios do COBOLware                   +
# CWPROMPT:    Indica de disponibilidade do COBOL default COBOLware 5.0 +
# CWROOT:      Diretorio inicial                                        +
# CWBAT:       Comando aditivo                                          +
#                                                                       +
#              Unix:                                                    +
#                                                                       +
# EDITOR:      Editor utilizado na instalacao                           +
# PATH:        Inclui utilitarios e fontes no caminho de pesquisa       +
#                                                                       +
#              Micro Focus:                                             +
#                                                                       +
# COBPATH:     Diretorios de pesquisa de modulos carga (.int e .gnt)    +
# dd_cobkeymp= Arquivo de configuracao de teclas (KEYBCF)               +
# dd_ADISCTRL= Arquivo de configuracao de teclas (ADISCF)               +
#                                                                       +
#-----------------------------------------------------------------------+


#-----------------------------------------------------------------------+
# Prompt para utilizar o COBOLware sem alterar o ambiente de producao
# do sistema ou do usuario                                              !
#-----------------------------------------------------------------------+

   if test -z "$1"
      then mkdir $CIL 2> /dev/null
           trap " " 1 2 3 15
           echo "COBOLware 6.0"
           echo "Copyright (C) 1984-2020 COBOLware Services Ltda."
           echo " "
           echo "Comande [exit] para voltar ao shell convencional"
           if test -z "$CWPROMPT"
              then CWPROMPT="COBOLware 6.1"
                   export CWPROMPT
           fi
           PS1='$CWPROMPT \u@\h `pwd`>'
           export PS1
           if test -z "$CWROOT"
              then echo " " > /dev/null
              else cd $CWROOT
           fi
           sh $CWBAT
     else if ! test -z "$CWBAT"
             then CWCOMMAND="$1 $2 $3 $4 $5 $6 $7 $8 $9"
                  export CWCOMMAND
                  $CWBAT
             else $1 $2 $3 $4 $5 $6 $7 $8 $9
          fi
   fi
fi
